target_table_and_cols= {'logplayermatchuserinfo': ['matchuserinfo'], 
 'logplayerposition': ['common',
  'character',
  'vehicle',
  'elapsedtime',
  'numaliveplayers'],
 'logplayertakedamage': ['common',
  'attackid',
  'attacker',
  'damagecausername',
  'victim',
  'damagetypecategory',
  'damagereason',
  'damage',
  'isthroughpenetrablewall'],
 'logplayerattack': ['common',
  'vehicle',
  'attackid',
  'fireweaponstackcount',
  'attacker',
  'attacktype',
  'weapon'],
 'logitempickup': ['common', 'character', 'item'],
 'logheal': ['common', 'character', 'item', 'healamount'],
 'logitemequip': ['common', 'character', 'item'],
 'logitemunequip': ['common', 'character', 'item'],
 'logitemuse': ['common', 'character', 'item'],
 'logitemattach': ['common', 'character', 'parentitem', 'childitem'],
 'logitemdetach': ['common', 'character', 'parentitem', 'childitem'],
 'logobjectinteraction': ['common',
  'character',
  'objecttype',
  'objecttypestatus',
  'objecttypeadditionalinfo'],
 'logitemdrop': ['common', 'character', 'item'],
 'logvehicledamage': ['common',
  'vehicle',
  'attackid',
  'attacker',
  'distance',
  'damagecausername',
  'damagetypecategory',
  'damage'],
 'logvehicleleave': ['common',
  'character',
  'vehicle',
  'seatindex',
  'fellowpassengers',
  'ridedistance',
  'maxspeed'],
 'logvehicleride': ['common',
  'character',
  'vehicle',
  'seatindex',
  'fellowpassengers'],
 'logobjectdestroy': ['common',
  'character',
  'objecttype',
  'objectlocation',
  'damagecausername'],
 'logvaultstart': ['common', 'character', 'isledgegrab', 'isvaultonvehicle'],
 'logweaponfirecount': ['common', 'character', 'weaponid', 'firecount'],
 'logitempickupfromlootbox': ['common',
  'character',
  'item',
  'ownerteamid',
  'creatoraccountid'],
 'loggamestateperiodic': ['common', 'gamestate'],
 'logplayerusethrowable': ['common',
  'attackid',
  'fireweaponstackcount',
  'attacker',
  'attacktype',
  'weapon'],
 'logparachutelanding': ['common', 'character', 'distance'],
 'logarmordestroy': ['common',
  'attackid',
  'attacker',
  'item',
  'distance',
  'damagecausername',
  'victim',
  'damagetypecategory',
  'damagereason'],
 'logplayermakegroggy': ['common',
  'attackid',
  'attacker',
  'distance',
  'damagecausername',
  'victim',
  'damagetypecategory',
  'damagereason',
  'isthroughpenetrablewall',
  'damagecauseradditionalinfo',
  'victimweapon',
  'victimweaponadditionalinfo',
  'isattackerinvehicle',
  'dbnoid'],
 'logplayerlogout': ['accountid', 'common'],
 'logplayerlogin': ['accountid', 'common'],
 'logplayercreate': ['common', 'character'],
 'logplayerkillv2': ['common',
  'attackid',
  'victim',
  'victimweapon',
  'victimweaponadditionalinfo',
  'dbnoid',
  'victimgameresult',
  'dbnomaker',
  'dbnodamageinfo',
  'finisher',
  'finishdamageinfo',
  'killer',
  'killerdamageinfo',
  'killervehicle',
  'assists_accountid',
  'teamkillers_accountid',
  'issuicide'],
 'logwheeldestroy': ['common',
  'vehicle',
  'attackid',
  'attacker',
  'damagecausername',
  'damagetypecategory',
  'wheelindex'],
 'logplayerrevive': ['common', 'victim', 'dbnoid', 'reviver', 'usetraumabag'],
 'logitemputtovehicletrunk': ['common', 'character', 'vehicle', 'item'],
 'logphasechange': ['common', 'phase', 'playersinwhitecircle'],
 'logitempickupfromcarepackage': ['common',
  'character',
  'item',
  'carepackageuniqueid',
  'carepackagename'],
 'logitempickupfromvehicletrunk': ['common', 'character', 'vehicle', 'item'],
 'logcharactercarry': ['common', 'character', 'carrystate'],
 'logcarepackagespawn': ['common', 'itempackage'],
 'logcarepackageland': ['common', 'itempackage'],
 'logswimend': ['common', 'character', 'swimdistance', 'maxswimdepthofwater'],
 'logvehicledestroy': ['common',
  'vehicle',
  'attackid',
  'attacker',
  'distance',
  'damagecausername',
  'damagetypecategory'],
 'logempickupliftoff': ['common', 'instigator', 'riders'],
 'logswimstart': ['common', 'character'],
 'logmatchstart': ['common',
  'mapname',
  'weatherid',
  'characters',
  'cameraviewbehaviour',
  'teamsize',
  'iscustomgame',
  'iseventmode',
  'bluezonecustomoptions'],
 'logmatchdefinition': ['matchid', 'submodeid', 'pingquality'],
 'logmatchend': ['common',
  'characters',
  'gameresultonfinished',
  'allweaponstats']}
